### PR TITLE
First tests

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**
* added autoconfig and gtest infra
* added simple loopback IBV_WR_SEND test

Signed-off-by: Kovalyov Artemy <artemyko@mellanox.com>

### CODE REVIEW

**Comment by Artemy-Mellanox** [comment]
> Change commit message to include test description and proper subject.

Please, help to build proper subject and message as you see it.

**Comment by rleon** [comment]
Subject: 
set initial GTEST infrastructure and add example loopback test
Message:
This commit sets GTEST infrastructure in the following format:
.... here_comes_description_of_folders ...

As an example of how-to use it, the loopback test was added.
---- here_comes_description_of_this_test...
=

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/2/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/6/ for details. (Mellanox internal link)

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/7/ for details. (Mellanox internal link)

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/8/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/10/ for details. (Mellanox internal link)

**Pull request closed without merging**
