### PR TITLE
ibverbs-tests: Add cross-channel tests for SEND_ENABLE directive

### PR DESCRIPTION
**Pull request by rleon**
Signed-off-by: Leon Romanovsky <leonro@mellanox.com>

### CODE REVIEW

**Comment by rleon** [comment]
@Artemy-Mellanox , @miked-mellanox  please review.

FYI: @igor-ivanov, @yosefe , @alex-mikheev

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/25/ for details. (Mellanox internal link)

**Comment by igor-ivanov** [comment]
:+1:

**Pull request merged**
