### PR TITLE
Topic/refactor

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/23/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/60/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/24/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/61/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/25/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/62/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/26/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/63/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/27/ for details (Mellanox internal link).

**Comment by Artemy-Mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/28/ for details (Mellanox internal link).

**Comment by mosesr76** [comment]
look fine for me, I will run it to test +1.

**Pull request merged**
