### PR TITLE
BUILD: add jenkins script

### PR DESCRIPTION
**Pull request by miked-mellanox**

### CODE REVIEW

**Comment by miked-mellanox** [comment]
@Di0gen - please check for jenkins

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/1/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/4/ for details. (Mellanox internal link)

**Pull request merged**
