### PR TITLE
Topic/cc query

### PR DESCRIPTION
**Pull request by rleon**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/14/ for details. (Mellanox internal link)

**Comment by rleon** [comment]
@miked-mellanox and @Artemy-Mellanox please review.

@vasilyMellanox, @yosefe , @alex-mikheev

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/15/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
