### PR TITLE
Topic/cc posts

### PR DESCRIPTION
**Pull request by rleon**
[----------] Global test environment tear-down
[==========] 35 tests from 9 test cases ran. (206761 ms total)
[  PASSED  ] 35 tests.

### CODE REVIEW

**Comment by rleon** [comment]
@Artemy-Mellanox , @miked-mellanox please review

FYI: @Igor-Ivanov, @yosefe and @alex-mikheev

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/27/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/28/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/29/ for details. (Mellanox internal link)

**Pull request merged**
