### PR TITLE
ibverbs-tests: Add basic peer-direct API tests

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**
Added test set ensuring that peer-direct functionality present and
conform API requirements.

Signed-off-by: Kovalyov Artemy <artemyko@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/16/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/17/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/18/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
