### PR TITLE
Topic/gtest

### PR DESCRIPTION
**Pull request by rleon**
This pull request contains:
* Directory structure creation
* GTEST infrastructure
* initial README file
* LICENSE file
* General initialization test

### CODE REVIEW

**Comment by rleon** [comment]
@Artemy-Mellanox and @miked-mellanox - please review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/11/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/12/ for details. (Mellanox internal link)

**Comment by rleon** [comment]
@Artemy-Mellanox, @miked-mellanox please review
@yosefe @vasilyMellanox @alex-mikheev

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/13/ for details. (Mellanox internal link)

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
