### PR TITLE
peer-direct: Use correct port during ibv_modify_qp

### PR DESCRIPTION
**Pull request by Artemy-Mellanox**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/53/ for details. (Mellanox internal link)

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ibverbs-tests-pr/54/ for details. (Mellanox internal link)

**Comment by mellanox-github** [comment]
Hi

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/18/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libverbs-tests-SimX-pr/19/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Pull request merged**
